version: "3.9"

services:
  nightwatch:
    build: nightwatch
    ports:
      - "5000:5000"
    volumes:
      - ./scripts:/scripts

  hub:
    image: selenium/hub:4
    environment:
      GRID_BROWSER_TIMEOUT: "120000"
      GRID_NEW_SESSION_WAIT_TIMEOUT: "8000"
      GRID_NODE_POLLING: "300"
      GRID_TIMEOUT: "120000"
    ports:
      - '4444:4444'

  node-chrome:
    image: selenium/node-chrome:4
    environment:
      SE_EVENT_BUS_HOST: "hub"
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
