version: "3.9"

services:
  nightwatch:
    build: nightwatch
    ports:
      - "5000:5000"
    depends_on:
      - node-chrome
      - selenium-hub
      - video-chrome
    volumes:
      - ./scripts:/scripts

  selenium-hub:
    image: selenium/hub:4
    environment:
      GRID_BROWSER_TIMEOUT: "120000"
      GRID_NEW_SESSION_WAIT_TIMEOUT: "8000"
      GRID_NODE_POLLING: "300"
      GRID_TIMEOUT: "120000"
    ports:
      - '4444:4444'

  node-chrome:
    image: selenium/node-chrome:4
    environment:
      SE_EVENT_BUS_HOST: "selenium-hub"
      SE_EVENT_BUS_PUBLISH_PORT: "4442"
      SE_EVENT_BUS_SUBSCRIBE_PORT: "4443"
    ports:
      - "6900:5900"

  # video only gets closed once the containers exits
  video-chrome:
    image: selenium/video:ffmpeg-4.3.1-20210426
    depends_on:
      - node-chrome
    volumes:
      - ./videos:/videos
    environment:
      DISPLAY_CONTAINER_NAME: node-chrome
      FILE_NAME: chrome_video.mp4